AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla CloudFormation para roles de IAM para ECS.

Resources:
  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: "/"
      Policies:
        - PolicyName: "ECSTaskExecutionPolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:*
                  - logs:*
                  - cloudwatch:*
                Resource: "*"

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: "/"
      Policies:
        - PolicyName: "ECSTaskPolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: "*" # Actualiza con ARNs específicos de Secrets Manager.

Outputs:
  ECSExecutionRoleArn:
    Description: "ARN of ECS Execution Role"
    Value: !GetAtt ECSExecutionRole.Arn
    Export:
      Name: ECSExecutionRole

  ECSTaskRoleArn:
    Description: "ARN of ECS Task Role"
    Value: !GetAtt ECSTaskRole.Arn
    Export:
      Name: ECSTaskRole